# [package]
# name = "contextfree"
# version = "0.1.0"
# edition = "2024"

# [dependencies]
# arrayvec = "0.7.6"
# bit-set = "0.8.0"

[package]
name = "contextfree"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
